name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # Required to push changes

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Generate snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: zayd100
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Show status
        if: always()
        run: git status

      - name: Commit and push changes
        if: steps.snake.outputs.snake_created == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Update snake animation [skip ci]"
          git push origin HEAD:main
