name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper git history

      # Step 2: Create output directory if it doesn't exist
      - name: Create dist directory
        run: mkdir -p dist

      # Step 3: Generate the snake animation
      - name: Generate contribution snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: zayd100  # Your GitHub username
          svg_out_path: dist/github-contribution-snake.svg
          gif_out_path: dist/github-contribution-snake.gif

      # Step 4: Debugging - verify files were created
      - name: Verify files
        run: |
          ls -la dist/
          [ -f dist/github-contribution-snake.svg ] && echo "SVG exists" || echo "SVG missing"
          [ -f dist/github-contribution-snake.gif ] && echo "GIF exists" || echo "GIF missing"

      # Step 5: Commit and push changes
      - name: Commit and push
        if: steps.snake.outputs.snake_created == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Update snake animation [skip ci]"
          git push
